services:
    caddy:
        container_name: caddy
        image: caddy:2
        networks:
            - bsky-pds
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        depends_on:
            - pds
        restart: unless-stopped
        volumes:
            - ./data/caddy/data:/data
            - ./data/caddy/etc/caddy:/etc/caddy
        env_file:
            - ./pds.env

    pds:
        container_name: pds
        image: ghcr.io/bluesky-social/pds:0.4
        restart: unless-stopped
        networks:
            - bsky-pds
        volumes:
            - ./data:/pds
        env_file:
            - ./pds.env

networks:
    bsky-pds:
        external: false
